controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - hand_motor_joint
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - head_pan_joint
      - head_tilt_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: arm_default
  - group: hand
    pose: hand_close