# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1
default_acceleration_scaling_factor: 1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_flex_joint:
    has_velocity_limits: false
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0
  arm_lift_joint:
    has_velocity_limits: false
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  arm_roll_joint:
    has_velocity_limits: false
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  hand_motor_joint:
    has_velocity_limits: false
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  hand_l_spring_proximal_joint:
    has_velocity_limits: false
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  hand_r_spring_proximal_joint:
    has_velocity_limits: false
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  head_pan_joint:
    has_velocity_limits: false
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  head_tilt_joint:
    has_velocity_limits: false
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_flex_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_roll_joint:
    has_velocity_limits: false
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 0
  odom_x:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.05
  odom_y:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 0.05
  odom_r:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.0