arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_lift_joint
    - arm_flex_joint
    - arm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint
  gains:
    arm_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_flex_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - hand_motor_joint
  gains:
    hand_motor_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
head_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - head_pan_joint
    - head_tilt_joint
  gains:
    head_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    head_tilt_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1