# footprint: [[-0.3, -0.3], [-0.3, 0.3],[0.3, 0.3], [0.3, -0.3]]
footprint: [[-0.085, -0.20], [-0.085, 0.2],[0.315, 0.2], [0.315, -0.2]]
#robot_radius: 0.30


obstacle_layer:
  enabled: true
  max_obstacle_height: 1.2
  min_obstacle_height: 0.0
  obstacle_range: 2.0
  raytrace_range: 5.0
  inflation_radius: 0.3
  combination_method: 1
  observation_sources: laser_scan_sensor  #sonar_scan_sensor
  track_unknown_space: true
 
  origin_z: 0.0
  z_resolution: 0.1
  z_voxels: 10
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: true
  footprint_clearing_enabled: true
  observation_persistence: 0.0
#expected_update_rate: 0.2
  laser_scan_sensor:
    data_type: LaserScan
    topic: /hsrb/base_scan
    marking: true
    clearing: true
    expected_update_rate: 0
    min_obstacle_height: 0.01
    max_obstacle_height: 0.1
    
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
